### ISSUE TITLE
[1.18.2] Warped Sacred and Wicked rites do not affect passive mobs.

### ISSUE THREAD

**Issue by DelviousCrafts** [SammySemicolon/Malum-Mod#158]
The book states that the warped sacred rite (soulwood totem + eldritch spirit) will make animals "vigorous" as though fed, indicating this will cause breeding. This does not occur with any mob I tested (sheep, pigs, chickens, cows). Attempted by placing them inside a 5x5 fence directly next to the active totem, then in a 5x5 fence directly in front of the active totem.

Similarly, testing the warped wicked rite (soulwood totem + eldritch spirit) does not cull any animals. In the same fencing areas as the sacred testing, spawned 50+ of previously mentioned mobs with no effect using mob spawn egg, most of which being adult animals. Unsure if this is due to the fact that they were spawned in with the spawn egg instead of naturally bred.

Noted there are pink particle effects floating in the air around the animals when the warped sacred rite is active, but no breeding effect is present. Both totems tested with the mobs at the same level as the totem base and one block below the totem base where some totems take effect.

Tested in a minimal environment with only Malum and required mods installed. 

Versions: 
Minecraft: 1.18.2
Forge: 40.2.0
Malum: 1.4.3.1
Lodestone: 1.2
Curios: 5.0.7.1

**Comment by SammySemicolon** [comment]
That's very strange, I haven't encountered this issue. 
I'll be updating the mod to a release version of 1.4 in a few days. It should be fixed then.

**Comment by SammySemicolon** [comment]
Let me know if it's fixed, Every time I tries it, always worked perfectly

**Comment by DelviousCrafts** [comment]
Sorry been waiting for another dependent mod to update to the newest version before updating in my standard pack. I did load up my mod bug test world with just Malum and requirements though. The warped sacred rite seems to be working great now, thank you. I'm still seeing no effect with the warped wicked rite.

Photo of setup
![Photo of setup](https://user-images.githubusercontent.com/46658624/213929190-0e55e233-9aa6-4904-a76f-6afa17651cb0.png)

I personally would consider this overcrowded, but maybe it's a higher entity count than I'm expecting that the ritual activates on. or perhaps I'm doing something incorrectly.

As a note: almost all of the pigs pictured here are spawned in with a spawn egg rather than with standard breeding.

**Comment by SammySemicolon** [comment]
I think- 
The sex rite only triggers if there are less than 30 entities in the area.
The kill rite only triggers if there are more than 30 entities in the area, and only targets entities that just gave birth.

Try placing like, 28 animals, and then it should work.

**Comment by DelviousCrafts** [comment]
Placed 28 animals initially using spawn eggs, and allowed the system to simply sit and run in the background to continue to test. Therefore baby animals were spawned, grew up, and had teeny weeny little piggies of their own through the power of the sex rite. 

This is the result of just idly sitting and allowing natural birthing to occur through the rite for about 2.5 hours.
![2023-01-22_15 36 37](https://user-images.githubusercontent.com/46658624/213944242-2c7a04cb-c2ea-400b-9f3c-044f93f41135.png)

The killing rite does not seem to be culling even when animals give birth.

**Comment by SammySemicolon** [comment]
I looked into it.
The kill rite had a small logic problem, instead of checking "are there more than 30 animals" we were checking "are there more than 30 animals who just made babies"
Fixed It.

**Comment by DelviousCrafts** [comment]
Awesome! Thank you so much for getting on top of this issue so quickly.
